name: memory_info_platform_interface
description: A common platform interface for memory_info.
repository: https://github.com/MrOlolo/memory_info/tree/master/memory_info_platform_interface
version: 0.0.2

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.8.0
  plugin_platform_interface: ^2.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter